modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "nethervinery"
version = "${version}"
displayName = "Nether Vinery"
authors = "satisfyu"
description = '''
Welcome to Nether Vinery! New grapes, new decor - all in the style of the Nether.
'''
#logoFile = ""

[[dependencies.nethervinery]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nethervinery]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nethervinery]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.nethervinery]]
modId = "vinery"
mandatory = true
versionRange = "[1.4.6,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.nethervinery]]
modId = "doapi"
mandatory = true
versionRange = "[1.2.7,)"
ordering = "AFTER"
side = "BOTH"